// fifo_w134d128_commonclock_sclr_showahead.v

// Generated using ACDS version 15.0 145

`timescale 1 ps / 1 ps
module fifo_w134d128_commonclock_sclr_showahead (
		input  wire [133:0] data,  //  fifo_input.datain
		input  wire         wrreq, //            .wrreq
		input  wire         rdreq, //            .rdreq(ack)
		input  wire         clock, //            .clk
		input  wire         sclr,  //            .sclr
		output wire [133:0] q,     // fifo_output.dataout
		output wire [6:0]   usedw, //            .usedw
		output wire         full,  //            .full
		output wire         empty  //            .empty
	);

	fifo_w134d128_commonclock_sclr_showahead_fifo_150_5kygyqi fifo_0 (
		.data  (data),  //  fifo_input.datain
		.wrreq (wrreq), //            .wrreq
		.rdreq (rdreq), //            .rdreq(ack)
		.clock (clock), //            .clk
		.sclr  (sclr),  //            .sclr
		.q     (q),     // fifo_output.dataout
		.usedw (usedw), //            .usedw
		.full  (full),  //            .full
		.empty (empty)  //            .empty
	);

endmodule
