config fifo_w12d4_commonclock_sclr_showahead_cfg;
		design fifo_w12d4_commonclock_sclr_showahead;
		instance fifo_w12d4_commonclock_sclr_showahead.fifo_0 use fifo_w12d4_commonclock_sclr_showahead_fifo_150.fifo_w12d4_commonclock_sclr_showahead_fifo_150_jwxjsei;
endconfig

