// fifo_35x4.v

// Generated using ACDS version 15.0 145

`timescale 1 ps / 1 ps
module fifo_35x4 (
		input  wire [34:0] data,  //  fifo_input.datain
		input  wire        wrreq, //            .wrreq
		input  wire        rdreq, //            .rdreq(ack)
		input  wire        clock, //            .clk
		input  wire        aclr,  //            .aclr
		output wire [34:0] q,     // fifo_output.dataout
		output wire [1:0]  usedw, //            .usedw
		output wire        full,  //            .full
		output wire        empty  //            .empty
	);

	fifo_35x4_fifo_150_uaxkwxy fifo_0 (
		.data  (data),  //  fifo_input.datain
		.wrreq (wrreq), //            .wrreq
		.rdreq (rdreq), //            .rdreq(ack)
		.clock (clock), //            .clk
		.aclr  (aclr),  //            .aclr
		.q     (q),     // fifo_output.dataout
		.usedw (usedw), //            .usedw
		.full  (full),  //            .full
		.empty (empty)  //            .empty
	);

endmodule
