// fifo_w12d4_commonclock_sclr_showahead.v

// Generated using ACDS version 19.1 670

`timescale 1 ps / 1 ps
module fifo_w12d4_commonclock_sclr_showahead (
		input  wire [11:0] data,  //  fifo_input.datain
		input  wire        wrreq, //            .wrreq
		input  wire        rdreq, //            .rdreq
		input  wire        clock, //            .clk
		input  wire        sclr,  //            .sclr
		output wire [11:0] q,     // fifo_output.dataout
		output wire [1:0]  usedw, //            .usedw
		output wire        full,  //            .full
		output wire        empty  //            .empty
	);

	fifo_w12d4_commonclock_sclr_showahead_fifo_191_l6hobiy fifo_0 (
		.data  (data),  //  fifo_input.datain
		.wrreq (wrreq), //            .wrreq
		.rdreq (rdreq), //            .rdreq
		.clock (clock), //            .clk
		.sclr  (sclr),  //            .sclr
		.q     (q),     // fifo_output.dataout
		.usedw (usedw), //            .usedw
		.full  (full),  //            .full
		.empty (empty)  //            .empty
	);

endmodule
