config sgmii_pcs_share_altera_lvds_191_xvdv7pi_cfg;
		design sgmii_pcs_share_altera_lvds_191_xvdv7pi;
		instance sgmii_pcs_share_altera_lvds_191_xvdv7pi.core use sgmii_pcs_share_altera_lvds_core20_191.sgmii_pcs_share_altera_lvds_core20_191_hbfz3py;
endconfig

