config sgmii_pcs_share_altera_eth_tse_191_mnifhha_cfg;
		design sgmii_pcs_share_altera_eth_tse_191_mnifhha;
		instance sgmii_pcs_share_altera_eth_tse_191_mnifhha.avalon_arbiter use sgmii_pcs_share_altera_eth_tse_avalon_arbiter_191.altera_eth_tse_avalon_arbiter;
		instance sgmii_pcs_share_altera_eth_tse_191_mnifhha.channel_adapter use sgmii_pcs_share_altera_eth_tse_channel_adapter_191.altera_eth_tse_channel_adapter;
		instance sgmii_pcs_share_altera_eth_tse_191_mnifhha.i_tse_fifoless_mac_0 use sgmii_pcs_share_altera_eth_tse_fifoless_mac_191.altera_eth_tse_fifoless_mac;
		instance sgmii_pcs_share_altera_eth_tse_191_mnifhha.i_tse_fifoless_mac_1 use sgmii_pcs_share_altera_eth_tse_fifoless_mac_191.altera_eth_tse_fifoless_mac;
		instance sgmii_pcs_share_altera_eth_tse_191_mnifhha.i_tse_fifoless_mac_2 use sgmii_pcs_share_altera_eth_tse_fifoless_mac_191.altera_eth_tse_fifoless_mac;
		instance sgmii_pcs_share_altera_eth_tse_191_mnifhha.i_tse_fifoless_mac_3 use sgmii_pcs_share_altera_eth_tse_fifoless_mac_191.altera_eth_tse_fifoless_mac;
		instance sgmii_pcs_share_altera_eth_tse_191_mnifhha.i_tse_pcs_0 use sgmii_pcs_share_altera_eth_tse_pcs_pma_nf_lvds_191.altera_eth_tse_pcs_pma_nf_lvds;
		instance sgmii_pcs_share_altera_eth_tse_191_mnifhha.i_lvdsio_rx_0 use sgmii_pcs_share_altera_lvds_191.sgmii_pcs_share_altera_lvds_191_xvdv7pi;
		instance sgmii_pcs_share_altera_eth_tse_191_mnifhha.i_lvdsio_tx_0 use sgmii_pcs_share_altera_lvds_191.sgmii_pcs_share_altera_lvds_191_id6gcay;
		instance sgmii_pcs_share_altera_eth_tse_191_mnifhha.i_lvdsio_terminator_0 use sgmii_pcs_share_altera_eth_tse_nf_lvds_terminator_191.altera_eth_tse_nf_lvds_terminator;
		instance sgmii_pcs_share_altera_eth_tse_191_mnifhha.i_tse_pcs_1 use sgmii_pcs_share_altera_eth_tse_pcs_pma_nf_lvds_191.altera_eth_tse_pcs_pma_nf_lvds;
		instance sgmii_pcs_share_altera_eth_tse_191_mnifhha.i_tse_pcs_2 use sgmii_pcs_share_altera_eth_tse_pcs_pma_nf_lvds_191.altera_eth_tse_pcs_pma_nf_lvds;
		instance sgmii_pcs_share_altera_eth_tse_191_mnifhha.i_tse_pcs_3 use sgmii_pcs_share_altera_eth_tse_pcs_pma_nf_lvds_191.altera_eth_tse_pcs_pma_nf_lvds;
		instance sgmii_pcs_share_altera_eth_tse_191_mnifhha.rst_controller use sgmii_pcs_share_altera_reset_controller_191.altera_reset_controller;
		instance sgmii_pcs_share_altera_eth_tse_191_mnifhha.rst_controller_001 use sgmii_pcs_share_altera_reset_controller_191.altera_reset_controller;
		instance sgmii_pcs_share_altera_eth_tse_191_mnifhha.rst_controller_002 use sgmii_pcs_share_altera_reset_controller_191.altera_reset_controller;
		instance sgmii_pcs_share_altera_eth_tse_191_mnifhha.rst_controller_003 use sgmii_pcs_share_altera_reset_controller_191.altera_reset_controller;
		instance sgmii_pcs_share_altera_eth_tse_191_mnifhha.rst_controller_004 use sgmii_pcs_share_altera_reset_controller_191.altera_reset_controller;
		instance sgmii_pcs_share_altera_eth_tse_191_mnifhha.rst_controller_005 use sgmii_pcs_share_altera_reset_controller_191.altera_reset_controller;
		instance sgmii_pcs_share_altera_eth_tse_191_mnifhha.rst_controller_006 use sgmii_pcs_share_altera_reset_controller_191.altera_reset_controller;
		instance sgmii_pcs_share_altera_eth_tse_191_mnifhha.rst_controller_007 use sgmii_pcs_share_altera_reset_controller_191.altera_reset_controller;
		instance sgmii_pcs_share_altera_eth_tse_191_mnifhha.rst_controller_008 use sgmii_pcs_share_altera_reset_controller_191.altera_reset_controller;
		instance sgmii_pcs_share_altera_eth_tse_191_mnifhha.rst_controller_009 use sgmii_pcs_share_altera_reset_controller_191.altera_reset_controller;
endconfig

