// sgmii_pcs_share.v

// Generated using ACDS version 19.1 670

`timescale 1 ps / 1 ps
module sgmii_pcs_share (
		input  wire        clk,            // control_port_clock_connection.clk
		input  wire        reset,          //              reset_connection.reset
		input  wire        ref_clk,        //  pcs_ref_clk_clock_connection.clk
        
		input  wire        rxp_0,            //             serial_connection.rxp_0
		output wire        txp_0,            //                              .txp_0
		input  wire [4:0]  reg_addr_0,       //                  control_port.address
		output wire [15:0] reg_data_out_0,   //                              .readdata
		input  wire        reg_rd_0,         //                              .read
		input  wire [15:0] reg_data_in_0,    //                              .writedata
		input  wire        reg_wr_0,         //                              .write
		output wire        reg_busy_0,       //                              .waitrequest
		output wire        tx_clk_0,         // pcs_transmit_clock_connection.clk
		output wire        rx_clk_0,         //  pcs_receive_clock_connection.clk
		input  wire        reset_tx_clk_0,   // pcs_transmit_reset_connection.reset
		input  wire        reset_rx_clk_0,   //  pcs_receive_reset_connection.reset
		output wire        gmii_rx_dv_0,     //               gmii_connection.gmii_rx_dv
		output wire [7:0]  gmii_rx_d_0,      //                              .gmii_rx_d
		output wire        gmii_rx_err_0,    //                              .gmii_rx_err
		input  wire        gmii_tx_en_0,     //                              .gmii_tx_en
		input  wire [7:0]  gmii_tx_d_0,      //                              .gmii_tx_d
		input  wire        gmii_tx_err_0,    //                              .gmii_tx_err
		output wire        led_crs_0,        //         status_led_connection.crs
		output wire        led_link_0,       //                              .link
		output wire        led_panel_link_0, //                              .panel_link
		output wire        led_col_0,        //                              .col
		output wire        led_an_0,         //                              .an
		output wire        led_char_err_0,   //                              .char_err
		output wire        led_disp_err_0,   //                              .disp_err
		output wire        rx_recovclkout_0,  //     serdes_control_connection.export
        
        input  wire        rxp_1,            //             serial_connection.rxp_1
		output wire        txp_1,            //                              .txp_1
		input  wire [4:0]  reg_addr_1,       //                  control_port.address
		output wire [15:0] reg_data_out_1,   //                              .readdata
		input  wire        reg_rd_1,         //                              .read
		input  wire [15:0] reg_data_in_1,    //                              .writedata
		input  wire        reg_wr_1,         //                              .write
		output wire        reg_busy_1,       //                              .waitrequest
		output wire        tx_clk_1,         // pcs_transmit_clock_connection.clk
		output wire        rx_clk_1,         //  pcs_receive_clock_connection.clk
		input  wire        reset_tx_clk_1,   // pcs_transmit_reset_connection.reset
		input  wire        reset_rx_clk_1,   //  pcs_receive_reset_connection.reset
		output wire        gmii_rx_dv_1,     //               gmii_connection.gmii_rx_dv
		output wire [7:0]  gmii_rx_d_1,      //                              .gmii_rx_d
		output wire        gmii_rx_err_1,    //                              .gmii_rx_err
		input  wire        gmii_tx_en_1,     //                              .gmii_tx_en
		input  wire [7:0]  gmii_tx_d_1,      //                              .gmii_tx_d
		input  wire        gmii_tx_err_1,    //                              .gmii_tx_err
		output wire        led_crs_1,        //         status_led_connection.crs
		output wire        led_link_1,       //                              .link
		output wire        led_panel_link_1, //                              .panel_link
		output wire        led_col_1,        //                              .col
		output wire        led_an_1,         //                              .an
		output wire        led_char_err_1,   //                              .char_err
		output wire        led_disp_err_1,   //                              .disp_err
		output wire        rx_recovclkout_1,  //     serdes_control_connection.export
        
        input  wire        rxp_2,            //             serial_connection.rxp_2
		output wire        txp_2,            //                              .txp_2
		input  wire [4:0]  reg_addr_2,       //                  control_port.address
		output wire [15:0] reg_data_out_2,   //                              .readdata
		input  wire        reg_rd_2,         //                              .read
		input  wire [15:0] reg_data_in_2,    //                              .writedata
		input  wire        reg_wr_2,         //                              .write
		output wire        reg_busy_2,       //                              .waitrequest
		output wire        tx_clk_2,         // pcs_transmit_clock_connection.clk
		output wire        rx_clk_2,         //  pcs_receive_clock_connection.clk
		input  wire        reset_tx_clk_2,   // pcs_transmit_reset_connection.reset
		input  wire        reset_rx_clk_2,   //  pcs_receive_reset_connection.reset
		output wire        gmii_rx_dv_2,     //               gmii_connection.gmii_rx_dv
		output wire [7:0]  gmii_rx_d_2,      //                              .gmii_rx_d
		output wire        gmii_rx_err_2,    //                              .gmii_rx_err
		input  wire        gmii_tx_en_2,     //                              .gmii_tx_en
		input  wire [7:0]  gmii_tx_d_2,      //                              .gmii_tx_d
		input  wire        gmii_tx_err_2,    //                              .gmii_tx_err
		output wire        led_crs_2,        //         status_led_connection.crs
		output wire        led_link_2,       //                              .link
		output wire        led_panel_link_2, //                              .panel_link
		output wire        led_col_2,        //                              .col
		output wire        led_an_2,         //                              .an
		output wire        led_char_err_2,   //                              .char_err
		output wire        led_disp_err_2,   //                              .disp_err
		output wire        rx_recovclkout_2,  //     serdes_control_connection.export
        
		input  wire        rxp_3,            //             serial_connection.rxp_3
		output wire        txp_3,            //                              .txp_3
		input  wire [4:0]  reg_addr_3,       //                  control_port.address
		output wire [15:0] reg_data_out_3,   //                              .readdata
		input  wire        reg_rd_3,         //                              .read
		input  wire [15:0] reg_data_in_3,    //                              .writedata
		input  wire        reg_wr_3,         //                              .write
		output wire        reg_busy_3,       //                              .waitrequest
		output wire        tx_clk_3,         // pcs_transmit_clock_connection.clk
		output wire        rx_clk_3,         //  pcs_receive_clock_connection.clk
		input  wire        reset_tx_clk_3,   // pcs_transmit_reset_connection.reset
		input  wire        reset_rx_clk_3,   //  pcs_receive_reset_connection.reset
		output wire        gmii_rx_dv_3,     //               gmii_connection.gmii_rx_dv
		output wire [7:0]  gmii_rx_d_3,      //                              .gmii_rx_d
		output wire        gmii_rx_err_3,    //                              .gmii_rx_err
		input  wire        gmii_tx_en_3,     //                              .gmii_tx_en
		input  wire [7:0]  gmii_tx_d_3,      //                              .gmii_tx_d
		input  wire        gmii_tx_err_3,    //                              .gmii_tx_err
		output wire        led_crs_3,        //         status_led_connection.crs
		output wire        led_link_3,       //                              .link
		output wire        led_panel_link_3, //                              .panel_link
		output wire        led_col_3,        //                              .col
		output wire        led_an_3,         //                              .an
		output wire        led_char_err_3,   //                              .char_err
		output wire        led_disp_err_3,   //                              .disp_err
		output wire        rx_recovclkout_3  //     serdes_control_connection.export
	);

	sgmii_pcs_share_altera_eth_tse_191_mnifhha eth_tse_0 (
		.clk            (clk),            // control_port_clock_connection.clk
		.reset          (reset),          //              reset_connection.reset
		.ref_clk        (ref_clk),        //  pcs_ref_clk_clock_connection.clk
        
		.rxp_0            (rxp_0),            //             serial_connection.rxp_0
		.txp_0            (txp_0),            //                              .txp_0
		.reg_addr_0       (reg_addr_0),       //                  control_port.address
		.reg_data_out_0   (reg_data_out_0),   //                              .readdata
		.reg_rd_0         (reg_rd_0),         //                              .read
		.reg_data_in_0    (reg_data_in_0),    //                              .writedata
		.reg_wr_0         (reg_wr_0),         //                              .write
		.reg_busy_0       (reg_busy_0),       //                              .waitrequest
		.tx_clk_0         (tx_clk_0),         // pcs_transmit_clock_connection.clk
		.rx_clk_0         (rx_clk_0),         //  pcs_receive_clock_connection.clk
		.reset_tx_clk_0   (reset_tx_clk_0),   // pcs_transmit_reset_connection.reset
		.reset_rx_clk_0   (reset_rx_clk_0),   //  pcs_receive_reset_connection.reset
		.gmii_rx_dv_0     (gmii_rx_dv_0),     //               gmii_connection.gmii_rx_dv
		.gmii_rx_d_0      (gmii_rx_d_0),      //                              .gmii_rx_d
		.gmii_rx_err_0    (gmii_rx_err_0),    //                              .gmii_rx_err
		.gmii_tx_en_0     (gmii_tx_en_0),     //                              .gmii_tx_en
		.gmii_tx_d_0      (gmii_tx_d_0),      //                              .gmii_tx_d
		.gmii_tx_err_0    (gmii_tx_err_0),    //                              .gmii_tx_err
		.led_crs_0        (led_crs_0),        //         status_led_connection.crs
		.led_link_0       (led_link_0),       //                              .link
		.led_panel_link_0 (led_panel_link_0), //                              .panel_link
		.led_col_0        (led_col_0),        //                              .col
		.led_an_0         (led_an_0),         //                              .an
		.led_char_err_0   (led_char_err_0),   //                              .char_err
		.led_disp_err_0   (led_disp_err_0),   //                              .disp_err
		.rx_recovclkout_0 (rx_recovclkout_0),  //     serdes_control_connection.export
        
		.rxp_1            (rxp_1),            //             serial_connection.rxp_1
		.txp_1            (txp_1),            //                              .txp_1
		.reg_addr_1       (reg_addr_1),       //                  control_port.address
		.reg_data_out_1   (reg_data_out_1),   //                              .readdata
		.reg_rd_1         (reg_rd_1),         //                              .read
		.reg_data_in_1    (reg_data_in_1),    //                              .writedata
		.reg_wr_1         (reg_wr_1),         //                              .write
		.reg_busy_1       (reg_busy_1),       //                              .waitrequest
		.tx_clk_1         (tx_clk_1),         // pcs_transmit_clock_connection.clk
		.rx_clk_1         (rx_clk_1),         //  pcs_receive_clock_connection.clk
		.reset_tx_clk_1   (reset_tx_clk_1),   // pcs_transmit_reset_connection.reset
		.reset_rx_clk_1   (reset_rx_clk_1),   //  pcs_receive_reset_connection.reset
		.gmii_rx_dv_1     (gmii_rx_dv_1),     //               gmii_connection.gmii_rx_dv
		.gmii_rx_d_1      (gmii_rx_d_1),      //                              .gmii_rx_d
		.gmii_rx_err_1    (gmii_rx_err_1),    //                              .gmii_rx_err
		.gmii_tx_en_1     (gmii_tx_en_1),     //                              .gmii_tx_en
		.gmii_tx_d_1      (gmii_tx_d_1),      //                              .gmii_tx_d
		.gmii_tx_err_1    (gmii_tx_err_1),    //                              .gmii_tx_err
		.led_crs_1        (led_crs_1),        //         status_led_connection.crs
		.led_link_1       (led_link_1),       //                              .link
		.led_panel_link_1 (led_panel_link_1), //                              .panel_link
		.led_col_1        (led_col_1),        //                              .col
		.led_an_1         (led_an_1),         //                              .an
		.led_char_err_1   (led_char_err_1),   //                              .char_err
		.led_disp_err_1   (led_disp_err_1),   //                              .disp_err
		.rx_recovclkout_1 (rx_recovclkout_1),  //     serdes_control_connection.export
        
        .rxp_2            (rxp_2),            //             serial_connection.rxp_2
		.txp_2            (txp_2),            //                              .txp_2
		.reg_addr_2       (reg_addr_2),       //                  control_port.address
		.reg_data_out_2   (reg_data_out_2),   //                              .readdata
		.reg_rd_2         (reg_rd_2),         //                              .read
		.reg_data_in_2    (reg_data_in_2),    //                              .writedata
		.reg_wr_2         (reg_wr_2),         //                              .write
		.reg_busy_2       (reg_busy_2),       //                              .waitrequest
		.tx_clk_2         (tx_clk_2),         // pcs_transmit_clock_connection.clk
		.rx_clk_2         (rx_clk_2),         //  pcs_receive_clock_connection.clk
		.reset_tx_clk_2   (reset_tx_clk_2),   // pcs_transmit_reset_connection.reset
		.reset_rx_clk_2   (reset_rx_clk_2),   //  pcs_receive_reset_connection.reset
		.gmii_rx_dv_2     (gmii_rx_dv_2),     //               gmii_connection.gmii_rx_dv
		.gmii_rx_d_2      (gmii_rx_d_2),      //                              .gmii_rx_d
		.gmii_rx_err_2    (gmii_rx_err_2),    //                              .gmii_rx_err
		.gmii_tx_en_2     (gmii_tx_en_2),     //                              .gmii_tx_en
		.gmii_tx_d_2      (gmii_tx_d_2),      //                              .gmii_tx_d
		.gmii_tx_err_2    (gmii_tx_err_2),    //                              .gmii_tx_err
		.led_crs_2        (led_crs_2),        //         status_led_connection.crs
		.led_link_2       (led_link_2),       //                              .link
		.led_panel_link_2 (led_panel_link_2), //                              .panel_link
		.led_col_2        (led_col_2),        //                              .col
		.led_an_2         (led_an_2),         //                              .an
		.led_char_err_2   (led_char_err_2),   //                              .char_err
		.led_disp_err_2   (led_disp_err_2),   //                              .disp_err
		.rx_recovclkout_2 (rx_recovclkout_2),  //     serdes_control_connection.export
        
        .rxp_3            (rxp_3),            //             serial_connection.rxp_3
		.txp_3            (txp_3),            //                              .txp_3
		.reg_addr_3       (reg_addr_3),       //                  control_port.address
		.reg_data_out_3   (reg_data_out_3),   //                              .readdata
		.reg_rd_3         (reg_rd_3),         //                              .read
		.reg_data_in_3    (reg_data_in_3),    //                              .writedata
		.reg_wr_3         (reg_wr_3),         //                              .write
		.reg_busy_3       (reg_busy_3),       //                              .waitrequest
		.tx_clk_3         (tx_clk_3),         // pcs_transmit_clock_connection.clk
		.rx_clk_3         (rx_clk_3),         //  pcs_receive_clock_connection.clk
		.reset_tx_clk_3   (reset_tx_clk_3),   // pcs_transmit_reset_connection.reset
		.reset_rx_clk_3   (reset_rx_clk_3),   //  pcs_receive_reset_connection.reset
		.gmii_rx_dv_3     (gmii_rx_dv_3),     //               gmii_connection.gmii_rx_dv
		.gmii_rx_d_3      (gmii_rx_d_3),      //                              .gmii_rx_d
		.gmii_rx_err_3    (gmii_rx_err_3),    //                              .gmii_rx_err
		.gmii_tx_en_3     (gmii_tx_en_3),     //                              .gmii_tx_en
		.gmii_tx_d_3      (gmii_tx_d_3),      //                              .gmii_tx_d
		.gmii_tx_err_3    (gmii_tx_err_3),    //                              .gmii_tx_err
		.led_crs_3        (led_crs_3),        //         status_led_connection.crs
		.led_link_3       (led_link_3),       //                              .link
		.led_panel_link_3 (led_panel_link_3), //                              .panel_link
		.led_col_3        (led_col_3),        //                              .col
		.led_an_3         (led_an_3),         //                              .an
		.led_char_err_3   (led_char_err_3),   //                              .char_err
		.led_disp_err_3   (led_disp_err_3),   //                              .disp_err
		.rx_recovclkout_3 (rx_recovclkout_3)  //     serdes_control_connection.export
	);

endmodule
