config ram_sdport_separaterwclock_rdaclr_w8d16_cfg;
		design ram_sdport_separaterwclock_rdaclr_w8d16;
		instance ram_sdport_separaterwclock_rdaclr_w8d16.ram_2port_0 use ram_sdport_separaterwclock_rdaclr_w8d16_ram_2port_191.ram_sdport_separaterwclock_rdaclr_w8d16_ram_2port_191_2sgz4hi;
endconfig

