// sgmii_pcs_share_altera_eth_tse_191_mnifhha.v

// This file was auto-generated from altera_eth_tse_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 19.1 670

`timescale 1 ps / 1 ps
module sgmii_pcs_share_altera_eth_tse_191_mnifhha (
		input  wire        clk,            // control_port_clock_connection.clk
		input  wire        reset,          //              reset_connection.reset
		input  wire        ref_clk,        //  pcs_ref_clk_clock_connection.clk
        
		input  wire        rxp_0,            //             serial_connection.rxp_0
		output wire        txp_0,            //                              .txp_0
		input  wire [4:0]  reg_addr_0,       //                  control_port.address
		output wire [15:0] reg_data_out_0,   //                              .readdata
		input  wire        reg_rd_0,         //                              .read
		input  wire [15:0] reg_data_in_0,    //                              .writedata
		input  wire        reg_wr_0,         //                              .write
		output wire        reg_busy_0,       //                              .waitrequest
		output wire        tx_clk_0,         // pcs_transmit_clock_connection.clk
		output wire        rx_clk_0,         //  pcs_receive_clock_connection.clk
		input  wire        reset_tx_clk_0,   // pcs_transmit_reset_connection.reset
		input  wire        reset_rx_clk_0,   //  pcs_receive_reset_connection.reset
		output wire        gmii_rx_dv_0,     //               gmii_connection.gmii_rx_dv
		output wire [7:0]  gmii_rx_d_0,      //                              .gmii_rx_d
		output wire        gmii_rx_err_0,    //                              .gmii_rx_err
		input  wire        gmii_tx_en_0,     //                              .gmii_tx_en
		input  wire [7:0]  gmii_tx_d_0,      //                              .gmii_tx_d
		input  wire        gmii_tx_err_0,    //                              .gmii_tx_err
		output wire        led_crs_0,        //         status_led_connection.crs
		output wire        led_link_0,       //                              .link
		output wire        led_panel_link_0, //                              .panel_link
		output wire        led_col_0,        //                              .col
		output wire        led_an_0,         //                              .an
		output wire        led_char_err_0,   //                              .char_err
		output wire        led_disp_err_0,   //                              .disp_err
		output wire        rx_recovclkout_0,  //     serdes_control_connection.export
        
        input  wire        rxp_1,            //             serial_connection.rxp_1
		output wire        txp_1,            //                              .txp_1
		input  wire [4:0]  reg_addr_1,       //                  control_port.address
		output wire [15:0] reg_data_out_1,   //                              .readdata
		input  wire        reg_rd_1,         //                              .read
		input  wire [15:0] reg_data_in_1,    //                              .writedata
		input  wire        reg_wr_1,         //                              .write
		output wire        reg_busy_1,       //                              .waitrequest
		output wire        tx_clk_1,         // pcs_transmit_clock_connection.clk
		output wire        rx_clk_1,         //  pcs_receive_clock_connection.clk
		input  wire        reset_tx_clk_1,   // pcs_transmit_reset_connection.reset
		input  wire        reset_rx_clk_1,   //  pcs_receive_reset_connection.reset
		output wire        gmii_rx_dv_1,     //               gmii_connection.gmii_rx_dv
		output wire [7:0]  gmii_rx_d_1,      //                              .gmii_rx_d
		output wire        gmii_rx_err_1,    //                              .gmii_rx_err
		input  wire        gmii_tx_en_1,     //                              .gmii_tx_en
		input  wire [7:0]  gmii_tx_d_1,      //                              .gmii_tx_d
		input  wire        gmii_tx_err_1,    //                              .gmii_tx_err
		output wire        led_crs_1,        //         status_led_connection.crs
		output wire        led_link_1,       //                              .link
		output wire        led_panel_link_1, //                              .panel_link
		output wire        led_col_1,        //                              .col
		output wire        led_an_1,         //                              .an
		output wire        led_char_err_1,   //                              .char_err
		output wire        led_disp_err_1,   //                              .disp_err
		output wire        rx_recovclkout_1,  //     serdes_control_connection.export
        
        input  wire        rxp_2,            //             serial_connection.rxp_2
		output wire        txp_2,            //                              .txp_2
		input  wire [4:0]  reg_addr_2,       //                  control_port.address
		output wire [15:0] reg_data_out_2,   //                              .readdata
		input  wire        reg_rd_2,         //                              .read
		input  wire [15:0] reg_data_in_2,    //                              .writedata
		input  wire        reg_wr_2,         //                              .write
		output wire        reg_busy_2,       //                              .waitrequest
		output wire        tx_clk_2,         // pcs_transmit_clock_connection.clk
		output wire        rx_clk_2,         //  pcs_receive_clock_connection.clk
		input  wire        reset_tx_clk_2,   // pcs_transmit_reset_connection.reset
		input  wire        reset_rx_clk_2,   //  pcs_receive_reset_connection.reset
		output wire        gmii_rx_dv_2,     //               gmii_connection.gmii_rx_dv
		output wire [7:0]  gmii_rx_d_2,      //                              .gmii_rx_d
		output wire        gmii_rx_err_2,    //                              .gmii_rx_err
		input  wire        gmii_tx_en_2,     //                              .gmii_tx_en
		input  wire [7:0]  gmii_tx_d_2,      //                              .gmii_tx_d
		input  wire        gmii_tx_err_2,    //                              .gmii_tx_err
		output wire        led_crs_2,        //         status_led_connection.crs
		output wire        led_link_2,       //                              .link
		output wire        led_panel_link_2, //                              .panel_link
		output wire        led_col_2,        //                              .col
		output wire        led_an_2,         //                              .an
		output wire        led_char_err_2,   //                              .char_err
		output wire        led_disp_err_2,   //                              .disp_err
		output wire        rx_recovclkout_2,  //     serdes_control_connection.export
        
		input  wire        rxp_3,            //             serial_connection.rxp_3
		output wire        txp_3,            //                              .txp_3
		input  wire [4:0]  reg_addr_3,       //                  control_port.address
		output wire [15:0] reg_data_out_3,   //                              .readdata
		input  wire        reg_rd_3,         //                              .read
		input  wire [15:0] reg_data_in_3,    //                              .writedata
		input  wire        reg_wr_3,         //                              .write
		output wire        reg_busy_3,       //                              .waitrequest
		output wire        tx_clk_3,         // pcs_transmit_clock_connection.clk
		output wire        rx_clk_3,         //  pcs_receive_clock_connection.clk
		input  wire        reset_tx_clk_3,   // pcs_transmit_reset_connection.reset
		input  wire        reset_rx_clk_3,   //  pcs_receive_reset_connection.reset
		output wire        gmii_rx_dv_3,     //               gmii_connection.gmii_rx_dv
		output wire [7:0]  gmii_rx_d_3,      //                              .gmii_rx_d
		output wire        gmii_rx_err_3,    //                              .gmii_rx_err
		input  wire        gmii_tx_en_3,     //                              .gmii_tx_en
		input  wire [7:0]  gmii_tx_d_3,      //                              .gmii_tx_d
		input  wire        gmii_tx_err_3,    //                              .gmii_tx_err
		output wire        led_crs_3,        //         status_led_connection.crs
		output wire        led_link_3,       //                              .link
		output wire        led_panel_link_3, //                              .panel_link
		output wire        led_col_3,        //                              .col
		output wire        led_an_3,         //                              .an
		output wire        led_char_err_3,   //                              .char_err
		output wire        led_disp_err_3,   //                              .disp_err
		output wire        rx_recovclkout_3  //     serdes_control_connection.export
	);

	wire         i_lvdsio_terminator_0_lvds_rx_inclock_export;                          // i_lvdsio_terminator_0:lvds_rx_inclock -> i_lvdsio_rx_0:inclock
	wire  [39:0] i_lvdsio_rx_0_rx_out_export;                                           // i_lvdsio_rx_0:rx_out -> i_lvdsio_terminator_0:rx_out
	wire   [3:0] i_lvdsio_terminator_0_rx_in_export;                                    // i_lvdsio_terminator_0:rx_in -> i_lvdsio_rx_0:rx_in
	wire   [3:0] i_lvdsio_terminator_0_rx_dpa_reset_export;                             // i_lvdsio_terminator_0:rx_dpa_reset -> i_lvdsio_rx_0:rx_dpa_reset
	wire   [3:0] i_lvdsio_rx_0_rx_dpa_locked_export;                                    // i_lvdsio_rx_0:rx_dpa_locked -> i_lvdsio_terminator_0:rx_dpa_locked
	wire   [3:0] i_lvdsio_rx_0_rx_divfwdclk_export;                                     // i_lvdsio_rx_0:rx_divfwdclk -> i_lvdsio_terminator_0:rx_divfwdclk
	wire         i_lvdsio_rx_0_rx_coreclock_export;                                     // i_lvdsio_rx_0:rx_coreclock -> i_lvdsio_terminator_0:rx_coreclock
	wire         i_lvdsio_rx_0_pll_locked_export;                                       // i_lvdsio_rx_0:pll_locked -> i_lvdsio_terminator_0:pll_locked_rx
	wire         i_lvdsio_terminator_0_pll_areset_rx_export;                            // i_lvdsio_terminator_0:pll_areset_rx -> i_lvdsio_rx_0:pll_areset
	wire         i_lvdsio_terminator_0_lvds_tx_inclock_export;                          // i_lvdsio_terminator_0:lvds_tx_inclock -> i_lvdsio_tx_0:inclock
	wire  [39:0] i_lvdsio_terminator_0_tx_in_export;                                    // i_lvdsio_terminator_0:tx_in -> i_lvdsio_tx_0:tx_in
	wire   [3:0] i_lvdsio_tx_0_tx_out_export;                                           // i_lvdsio_tx_0:tx_out -> i_lvdsio_terminator_0:tx_out
	wire         i_lvdsio_tx_0_pll_locked_export;                                       // i_lvdsio_tx_0:pll_locked -> i_lvdsio_terminator_0:pll_locked_tx
	wire         i_lvdsio_terminator_0_pll_areset_tx_export; 
    
	wire  [9:0] i_tse_pcs_0_tbi_tx_d_muxed_tbi_tx_d_muxed;                             // i_tse_pcs_0:tbi_tx_d_muxed -> i_lvdsio_terminator_0:tbi_tx_d_muxed_0
	wire  [9:0] i_lvdsio_terminator_0_tbi_rx_d_lvds_0_tbi_rx_d_lvds;                   // i_lvdsio_terminator_0:tbi_rx_d_lvds_0 -> i_tse_pcs_0:tbi_rx_d_lvds
	wire        i_lvdsio_terminator_0_tbi_rx_clk_0_tbi_rx_clk;                         // i_lvdsio_terminator_0:tbi_rx_clk_0 -> i_tse_pcs_0:tbi_rx_clk
	wire        i_lvdsio_terminator_0_rx_reset_sequence_done_0_rx_reset_sequence_done; // i_lvdsio_terminator_0:rx_reset_sequence_done_0 -> i_tse_pcs_0:rx_reset_sequence_done
	wire        i_lvdsio_terminator_0_rx_reset_0_rx_reset;                             // i_lvdsio_terminator_0:rx_reset_0 -> i_tse_pcs_0:rx_reset
	wire        i_lvdsio_terminator_0_tx_reset_0_tx_reset;                             // i_lvdsio_terminator_0:tx_reset_0 -> i_tse_pcs_0:tx_reset
    
	wire  [9:0] i_tse_pcs_1_tbi_tx_d_muxed_tbi_tx_d_muxed;                             // i_tse_pcs_1:tbi_tx_d_muxed -> i_lvdsio_terminator_0:tbi_tx_d_muxed_1
	wire  [9:0] i_lvdsio_terminator_0_tbi_rx_d_lvds_1_tbi_rx_d_lvds;                   // i_lvdsio_terminator_0:tbi_rx_d_lvds_1 -> i_tse_pcs_1:tbi_rx_d_lvds
	wire        i_lvdsio_terminator_0_tbi_rx_clk_1_tbi_rx_clk;                         // i_lvdsio_terminator_0:tbi_rx_clk_1 -> i_tse_pcs_1:tbi_rx_clk
	wire        i_lvdsio_terminator_0_rx_reset_sequence_done_1_rx_reset_sequence_done; // i_lvdsio_terminator_0:rx_reset_sequence_done_1 -> i_tse_pcs_1:rx_reset_sequence_done
	wire        i_lvdsio_terminator_0_rx_reset_1_rx_reset;                             // i_lvdsio_terminator_0:rx_reset_1 -> i_tse_pcs_0:rx_reset
	wire        i_lvdsio_terminator_0_tx_reset_1_tx_reset;                             // i_lvdsio_terminator_0:tx_reset_1 -> i_tse_pcs_0:tx_reset   
    
	wire  [9:0] i_tse_pcs_2_tbi_tx_d_muxed_tbi_tx_d_muxed;                             // i_tse_pcs_2:tbi_tx_d_muxed -> i_lvdsio_terminator_0:tbi_tx_d_muxed_2
	wire  [9:0] i_lvdsio_terminator_0_tbi_rx_d_lvds_2_tbi_rx_d_lvds;                   // i_lvdsio_terminator_0:tbi_rx_d_lvds_2 -> i_tse_pcs_2:tbi_rx_d_lvds
	wire        i_lvdsio_terminator_0_tbi_rx_clk_2_tbi_rx_clk;                         // i_lvdsio_terminator_0:tbi_rx_clk_2 -> i_tse_pcs_2:tbi_rx_clk
	wire        i_lvdsio_terminator_0_rx_reset_sequence_done_2_rx_reset_sequence_done; // i_lvdsio_terminator_0:rx_reset_sequence_done_2 -> i_tse_pcs_2:rx_reset_sequence_done
	wire        i_lvdsio_terminator_0_rx_reset_2_rx_reset;                             // i_lvdsio_terminator_0:rx_reset_2 -> i_tse_pcs_0:rx_reset
	wire        i_lvdsio_terminator_0_tx_reset_2_tx_reset;                             // i_lvdsio_terminator_0:tx_reset_2 -> i_tse_pcs_0:tx_reset   
    
	wire  [9:0] i_tse_pcs_3_tbi_tx_d_muxed_tbi_tx_d_muxed;                             // i_tse_pcs_3:tbi_tx_d_muxed -> i_lvdsio_terminator_0:tbi_tx_d_muxed_3
	wire  [9:0] i_lvdsio_terminator_0_tbi_rx_d_lvds_3_tbi_rx_d_lvds;                   // i_lvdsio_terminator_0:tbi_rx_d_lvds_3 -> i_tse_pcs_3:tbi_rx_d_lvds
	wire        i_lvdsio_terminator_0_tbi_rx_clk_3_tbi_rx_clk;                         // i_lvdsio_terminator_0:tbi_rx_clk_3 -> i_tse_pcs_3:tbi_rx_clk
	wire        i_lvdsio_terminator_0_rx_reset_sequence_done_3_rx_reset_sequence_done; // i_lvdsio_terminator_0:rx_reset_sequence_done_3 -> i_tse_pcs_3:rx_reset_sequence_done
	wire        i_lvdsio_terminator_0_rx_reset_3_rx_reset;                             // i_lvdsio_terminator_0:rx_reset_3 -> i_tse_pcs_0:rx_reset
	wire        i_lvdsio_terminator_0_tx_reset_3_tx_reset;                             // i_lvdsio_terminator_0:tx_reset_3 -> i_tse_pcs_0:tx_reset   
    
	wire        rst_controller_reset_out_reset;                                        // rst_controller:reset_out -> i_lvdsio_terminator_0:reset

	altera_eth_tse_pcs_pma_nf_lvds #(
		.ENABLE_TIMESTAMPING (0),
		.DEV_VERSION         (4865),
		.ENABLE_ECC          (0),
		.ENABLE_REV_LOOPBACK (0),
		.DEVICE_FAMILY       ("ARRIA10"),
		.SYNCHRONIZER_DEPTH  (3),
		.ENABLE_CLK_SHARING  (1),
		.ENABLE_SGMII        (0),
		.PHY_IDENTIFIER      (0)
	) i_tse_pcs_0 (
		.clk                    (clk),                                                                   // control_port_clock_connection.clk
		.reset                  (reset),                                                                 //              reset_connection.reset
		.reg_addr               (reg_addr_0),                                                              //                  control_port.address
		.reg_data_out           (reg_data_out_0),                                                          //                              .readdata
		.reg_rd                 (reg_rd_0),                                                                //                              .read
		.reg_data_in            (reg_data_in_0),                                                           //                              .writedata
		.reg_wr                 (reg_wr_0),                                                                //                              .write
		.reg_busy               (reg_busy_0),                                                              //                              .waitrequest
		.ref_clk                (ref_clk),                                                               //  pcs_ref_clk_clock_connection.clk
		.gmii_rx_dv             (gmii_rx_dv_0),                                                            //               gmii_connection.gmii_rx_dv
		.gmii_rx_d              (gmii_rx_d_0),                                                             //                              .gmii_rx_d
		.gmii_rx_err            (gmii_rx_err_0),                                                           //                              .gmii_rx_err
		.gmii_tx_en             (gmii_tx_en_0),                                                            //                              .gmii_tx_en
		.gmii_tx_d              (gmii_tx_d_0),                                                             //                              .gmii_tx_d
		.gmii_tx_err            (gmii_tx_err_0),                                                           //                              .gmii_tx_err
		.tx_clk                 (tx_clk_0),                                                                // pcs_transmit_clock_connection.clk
		.rx_clk                 (rx_clk_0),                                                                //  pcs_receive_clock_connection.clk
		.reset_tx_clk           (reset_tx_clk_0),                                                          // pcs_transmit_reset_connection.reset
		.reset_rx_clk           (reset_rx_clk_0),                                                          //  pcs_receive_reset_connection.reset
		.led_crs                (led_crs_0),                                                               //         status_led_connection.export
		.led_link               (led_link_0),                                                              //                              .export
		.led_panel_link         (led_panel_link_0),                                                        //                              .export
		.led_col                (led_col_0),                                                               //                              .export
		.led_an                 (led_an_0),                                                                //                              .export
		.led_char_err           (led_char_err_0),                                                          //                              .export
		.led_disp_err           (led_disp_err_0),                                                          //                              .export
		.rx_recovclkout         (rx_recovclkout_0),                                                        //     serdes_control_connection.export
        
		.rx_reset               (i_lvdsio_terminator_0_rx_reset_0_rx_reset),                             //                      rx_reset.rx_reset
		.rx_reset_sequence_done (i_lvdsio_terminator_0_rx_reset_sequence_done_0_rx_reset_sequence_done), //        rx_reset_sequence_done.rx_reset_sequence_done
		.tbi_rx_clk             (i_lvdsio_terminator_0_tbi_rx_clk_0_tbi_rx_clk),                         //                    tbi_rx_clk.tbi_rx_clk
		.tx_reset               (i_lvdsio_terminator_0_tx_reset_0_tx_reset),                             //                      tx_reset.tx_reset
		.tbi_tx_d_muxed         (i_tse_pcs_0_tbi_tx_d_muxed_tbi_tx_d_muxed),                             //                tbi_tx_d_muxed.tbi_tx_d_muxed
		.tbi_rx_d_lvds          (i_lvdsio_terminator_0_tbi_rx_d_lvds_0_tbi_rx_d_lvds),                   //                 tbi_rx_d_lvds.tbi_rx_d_lvds
        
		.tx_clkena              (),                                                                      //                   (terminated)
		.rx_clkena              (),                                                                      //                   (terminated)
		.mii_rx_dv              (),                                                                      //                   (terminated)
		.mii_rx_d               (),                                                                      //                   (terminated)
		.mii_rx_err             (),                                                                      //                   (terminated)
		.mii_tx_en              (1'b0),                                                                  //                   (terminated)
		.mii_tx_d               (4'b0000),                                                               //                   (terminated)
		.mii_tx_err             (1'b0),                                                                  //                   (terminated)
		.mii_col                (),                                                                      //                   (terminated)
		.mii_crs                (),                                                                      //                   (terminated)
		.set_10                 (),                                                                      //                   (terminated)
		.set_1000               (),                                                                      //                   (terminated)
		.set_100                (),                                                                      //                   (terminated)
		.hd_ena                 (),                                                                      //                   (terminated)
		.pcs_phase_measure_clk  (1'b0),                                                                  //                   (terminated)
		.rx_latency_adj         (),                                                                      //                   (terminated)
		.tx_latency_adj         (),                                                                      //                   (terminated)
		.tx_ptp_alignment       (),                                                                      //                   (terminated)
		.pcs_eccstatus          ()                                                                       //                   (terminated)
	);

	altera_eth_tse_pcs_pma_nf_lvds #(
		.ENABLE_TIMESTAMPING (0),
		.DEV_VERSION         (4865),
		.ENABLE_ECC          (0),
		.ENABLE_REV_LOOPBACK (0),
		.DEVICE_FAMILY       ("ARRIA10"),
		.SYNCHRONIZER_DEPTH  (3),
		.ENABLE_CLK_SHARING  (1),
		.ENABLE_SGMII        (0),
		.PHY_IDENTIFIER      (0)
	) i_tse_pcs_1 (
		.clk                    (clk),                                                                   // control_port_clock_connection.clk
		.reset                  (reset),                                                                 //              reset_connection.reset
		.reg_addr               (reg_addr_1),                                                              //                  control_port.address
		.reg_data_out           (reg_data_out_1),                                                          //                              .readdata
		.reg_rd                 (reg_rd_1),                                                                //                              .read
		.reg_data_in            (reg_data_in_1),                                                           //                              .writedata
		.reg_wr                 (reg_wr_1),                                                                //                              .write
		.reg_busy               (reg_busy_1),                                                              //                              .waitrequest
		.ref_clk                (ref_clk),                                                               //  pcs_ref_clk_clock_connection.clk
		.gmii_rx_dv             (gmii_rx_dv_1),                                                            //               gmii_connection.gmii_rx_dv
		.gmii_rx_d              (gmii_rx_d_1),                                                             //                              .gmii_rx_d
		.gmii_rx_err            (gmii_rx_err_1),                                                           //                              .gmii_rx_err
		.gmii_tx_en             (gmii_tx_en_1),                                                            //                              .gmii_tx_en
		.gmii_tx_d              (gmii_tx_d_1),                                                             //                              .gmii_tx_d
		.gmii_tx_err            (gmii_tx_err_1),                                                           //                              .gmii_tx_err
		.tx_clk                 (tx_clk_1),                                                                // pcs_transmit_clock_connection.clk
		.rx_clk                 (rx_clk_1),                                                                //  pcs_receive_clock_connection.clk
		.reset_tx_clk           (reset_tx_clk_1),                                                          // pcs_transmit_reset_connection.reset
		.reset_rx_clk           (reset_rx_clk_1),                                                          //  pcs_receive_reset_connection.reset
		.led_crs                (led_crs_1),                                                               //         status_led_connection.export
		.led_link               (led_link_1),                                                              //                              .export
		.led_panel_link         (led_panel_link_1),                                                        //                              .export
		.led_col                (led_col_1),                                                               //                              .export
		.led_an                 (led_an_1),                                                                //                              .export
		.led_char_err           (led_char_err_1),                                                          //                              .export
		.led_disp_err           (led_disp_err_1),                                                          //                              .export
		.rx_recovclkout         (rx_recovclkout_1),                                                        //     serdes_control_connection.export
        
		.rx_reset               (i_lvdsio_terminator_0_rx_reset_1_rx_reset),                             //                      rx_reset.rx_reset
		.rx_reset_sequence_done (i_lvdsio_terminator_0_rx_reset_sequence_done_1_rx_reset_sequence_done), //        rx_reset_sequence_done.rx_reset_sequence_done
		.tbi_rx_clk             (i_lvdsio_terminator_0_tbi_rx_clk_1_tbi_rx_clk),                         //                    tbi_rx_clk.tbi_rx_clk
		.tx_reset               (i_lvdsio_terminator_0_tx_reset_1_tx_reset),                             //                      tx_reset.tx_reset
		.tbi_tx_d_muxed         (i_tse_pcs_1_tbi_tx_d_muxed_tbi_tx_d_muxed),                             //                tbi_tx_d_muxed.tbi_tx_d_muxed
		.tbi_rx_d_lvds          (i_lvdsio_terminator_0_tbi_rx_d_lvds_1_tbi_rx_d_lvds),                   //                 tbi_rx_d_lvds.tbi_rx_d_lvds
        
		.tx_clkena              (),                                                                      //                   (terminated)
		.rx_clkena              (),                                                                      //                   (terminated)
		.mii_rx_dv              (),                                                                      //                   (terminated)
		.mii_rx_d               (),                                                                      //                   (terminated)
		.mii_rx_err             (),                                                                      //                   (terminated)
		.mii_tx_en              (1'b0),                                                                  //                   (terminated)
		.mii_tx_d               (4'b0000),                                                               //                   (terminated)
		.mii_tx_err             (1'b0),                                                                  //                   (terminated)
		.mii_col                (),                                                                      //                   (terminated)
		.mii_crs                (),                                                                      //                   (terminated)
		.set_10                 (),                                                                      //                   (terminated)
		.set_1000               (),                                                                      //                   (terminated)
		.set_100                (),                                                                      //                   (terminated)
		.hd_ena                 (),                                                                      //                   (terminated)
		.pcs_phase_measure_clk  (1'b0),                                                                  //                   (terminated)
		.rx_latency_adj         (),                                                                      //                   (terminated)
		.tx_latency_adj         (),                                                                      //                   (terminated)
		.tx_ptp_alignment       (),                                                                      //                   (terminated)
		.pcs_eccstatus          ()                                                                       //                   (terminated)
	);
    
    altera_eth_tse_pcs_pma_nf_lvds #(
		.ENABLE_TIMESTAMPING (0),
		.DEV_VERSION         (4865),
		.ENABLE_ECC          (0),
		.ENABLE_REV_LOOPBACK (0),
		.DEVICE_FAMILY       ("ARRIA10"),
		.SYNCHRONIZER_DEPTH  (3),
		.ENABLE_CLK_SHARING  (1),
		.ENABLE_SGMII        (0),
		.PHY_IDENTIFIER      (0)
	) i_tse_pcs_2 (
		.clk                    (clk),                                                                   // control_port_clock_connection.clk
		.reset                  (reset),                                                                 //              reset_connection.reset
		.reg_addr               (reg_addr_2),                                                              //                  control_port.address
		.reg_data_out           (reg_data_out_2),                                                          //                              .readdata
		.reg_rd                 (reg_rd_2),                                                                //                              .read
		.reg_data_in            (reg_data_in_2),                                                           //                              .writedata
		.reg_wr                 (reg_wr_2),                                                                //                              .write
		.reg_busy               (reg_busy_2),                                                              //                              .waitrequest
		.ref_clk                (ref_clk),                                                               //  pcs_ref_clk_clock_connection.clk
		.gmii_rx_dv             (gmii_rx_dv_2),                                                            //               gmii_connection.gmii_rx_dv
		.gmii_rx_d              (gmii_rx_d_2),                                                             //                              .gmii_rx_d
		.gmii_rx_err            (gmii_rx_err_2),                                                           //                              .gmii_rx_err
		.gmii_tx_en             (gmii_tx_en_2),                                                            //                              .gmii_tx_en
		.gmii_tx_d              (gmii_tx_d_2),                                                             //                              .gmii_tx_d
		.gmii_tx_err            (gmii_tx_err_2),                                                           //                              .gmii_tx_err
		.tx_clk                 (tx_clk_2),                                                                // pcs_transmit_clock_connection.clk
		.rx_clk                 (rx_clk_2),                                                                //  pcs_receive_clock_connection.clk
		.reset_tx_clk           (reset_tx_clk_2),                                                          // pcs_transmit_reset_connection.reset
		.reset_rx_clk           (reset_rx_clk_2),                                                          //  pcs_receive_reset_connection.reset
		.led_crs                (led_crs_2),                                                               //         status_led_connection.export
		.led_link               (led_link_2),                                                              //                              .export
		.led_panel_link         (led_panel_link_2),                                                        //                              .export
		.led_col                (led_col_2),                                                               //                              .export
		.led_an                 (led_an_2),                                                                //                              .export
		.led_char_err           (led_char_err_2),                                                          //                              .export
		.led_disp_err           (led_disp_err_2),                                                          //                              .export
		.rx_recovclkout         (rx_recovclkout_2),                                                        //     serdes_control_connection.export
        
		.rx_reset               (i_lvdsio_terminator_0_rx_reset_2_rx_reset),                             //                      rx_reset.rx_reset
		.rx_reset_sequence_done (i_lvdsio_terminator_0_rx_reset_sequence_done_2_rx_reset_sequence_done), //        rx_reset_sequence_done.rx_reset_sequence_done
		.tbi_rx_clk             (i_lvdsio_terminator_0_tbi_rx_clk_2_tbi_rx_clk),                         //                    tbi_rx_clk.tbi_rx_clk
		.tx_reset               (i_lvdsio_terminator_0_tx_reset_2_tx_reset),                             //                      tx_reset.tx_reset
		.tbi_tx_d_muxed         (i_tse_pcs_2_tbi_tx_d_muxed_tbi_tx_d_muxed),                             //                tbi_tx_d_muxed.tbi_tx_d_muxed
		.tbi_rx_d_lvds          (i_lvdsio_terminator_0_tbi_rx_d_lvds_2_tbi_rx_d_lvds),                   //                 tbi_rx_d_lvds.tbi_rx_d_lvds
        
		.tx_clkena              (),                                                                      //                   (terminated)
		.rx_clkena              (),                                                                      //                   (terminated)
		.mii_rx_dv              (),                                                                      //                   (terminated)
		.mii_rx_d               (),                                                                      //                   (terminated)
		.mii_rx_err             (),                                                                      //                   (terminated)
		.mii_tx_en              (1'b0),                                                                  //                   (terminated)
		.mii_tx_d               (4'b0000),                                                               //                   (terminated)
		.mii_tx_err             (1'b0),                                                                  //                   (terminated)
		.mii_col                (),                                                                      //                   (terminated)
		.mii_crs                (),                                                                      //                   (terminated)
		.set_20                 (),                                                                      //                   (terminated)
		.set_2000               (),                                                                      //                   (terminated)
		.set_200                (),                                                                      //                   (terminated)
		.hd_ena                 (),                                                                      //                   (terminated)
		.pcs_phase_measure_clk  (1'b0),                                                                  //                   (terminated)
		.rx_latency_adj         (),                                                                      //                   (terminated)
		.tx_latency_adj         (),                                                                      //                   (terminated)
		.tx_ptp_alignment       (),                                                                      //                   (terminated)
		.pcs_eccstatus          ()                                                                       //                   (terminated)
	);

	altera_eth_tse_pcs_pma_nf_lvds #(
		.ENABLE_TIMESTAMPING (0),
		.DEV_VERSION         (4865),
		.ENABLE_ECC          (0),
		.ENABLE_REV_LOOPBACK (0),
		.DEVICE_FAMILY       ("ARRIA10"),
		.SYNCHRONIZER_DEPTH  (3),
		.ENABLE_CLK_SHARING  (1),
		.ENABLE_SGMII        (0),
		.PHY_IDENTIFIER      (0)
	) i_tse_pcs_3 (
		.clk                    (clk),                                                                   // control_port_clock_connection.clk
		.reset                  (reset),                                                                 //              reset_connection.reset
		.reg_addr               (reg_addr_3),                                                              //                  control_port.address
		.reg_data_out           (reg_data_out_3),                                                          //                              .readdata
		.reg_rd                 (reg_rd_3),                                                                //                              .read
		.reg_data_in            (reg_data_in_3),                                                           //                              .writedata
		.reg_wr                 (reg_wr_3),                                                                //                              .write
		.reg_busy               (reg_busy_3),                                                              //                              .waitrequest
		.ref_clk                (ref_clk),                                                               //  pcs_ref_clk_clock_connection.clk
		.gmii_rx_dv             (gmii_rx_dv_3),                                                            //               gmii_connection.gmii_rx_dv
		.gmii_rx_d              (gmii_rx_d_3),                                                             //                              .gmii_rx_d
		.gmii_rx_err            (gmii_rx_err_3),                                                           //                              .gmii_rx_err
		.gmii_tx_en             (gmii_tx_en_3),                                                            //                              .gmii_tx_en
		.gmii_tx_d              (gmii_tx_d_3),                                                             //                              .gmii_tx_d
		.gmii_tx_err            (gmii_tx_err_3),                                                           //                              .gmii_tx_err
		.tx_clk                 (tx_clk_3),                                                                // pcs_transmit_clock_connection.clk
		.rx_clk                 (rx_clk_3),                                                                //  pcs_receive_clock_connection.clk
		.reset_tx_clk           (reset_tx_clk_3),                                                          // pcs_transmit_reset_connection.reset
		.reset_rx_clk           (reset_rx_clk_3),                                                          //  pcs_receive_reset_connection.reset
		.led_crs                (led_crs_3),                                                               //         status_led_connection.export
		.led_link               (led_link_3),                                                              //                              .export
		.led_panel_link         (led_panel_link_3),                                                        //                              .export
		.led_col                (led_col_3),                                                               //                              .export
		.led_an                 (led_an_3),                                                                //                              .export
		.led_char_err           (led_char_err_3),                                                          //                              .export
		.led_disp_err           (led_disp_err_3),                                                          //                              .export
		.rx_recovclkout         (rx_recovclkout_3),                                                        //     serdes_control_connection.export
        
		.rx_reset               (i_lvdsio_terminator_0_rx_reset_3_rx_reset),                             //                      rx_reset.rx_reset
		.rx_reset_sequence_done (i_lvdsio_terminator_0_rx_reset_sequence_done_3_rx_reset_sequence_done), //        rx_reset_sequence_done.rx_reset_sequence_done
		.tbi_rx_clk             (i_lvdsio_terminator_0_tbi_rx_clk_3_tbi_rx_clk),                         //                    tbi_rx_clk.tbi_rx_clk
		.tx_reset               (i_lvdsio_terminator_0_tx_reset_3_tx_reset),                             //                      tx_reset.tx_reset
		.tbi_tx_d_muxed         (i_tse_pcs_3_tbi_tx_d_muxed_tbi_tx_d_muxed),                             //                tbi_tx_d_muxed.tbi_tx_d_muxed
		.tbi_rx_d_lvds          (i_lvdsio_terminator_0_tbi_rx_d_lvds_3_tbi_rx_d_lvds),                   //                 tbi_rx_d_lvds.tbi_rx_d_lvds
        
		.tx_clkena              (),                                                                      //                   (terminated)
		.rx_clkena              (),                                                                      //                   (terminated)
		.mii_rx_dv              (),                                                                      //                   (terminated)
		.mii_rx_d               (),                                                                      //                   (terminated)
		.mii_rx_err             (),                                                                      //                   (terminated)
		.mii_tx_en              (1'b0),                                                                  //                   (terminated)
		.mii_tx_d               (4'b0000),                                                               //                   (terminated)
		.mii_tx_err             (1'b0),                                                                  //                   (terminated)
		.mii_col                (),                                                                      //                   (terminated)
		.mii_crs                (),                                                                      //                   (terminated)
		.set_30                 (),                                                                      //                   (terminated)
		.set_3000               (),                                                                      //                   (terminated)
		.set_300                (),                                                                      //                   (terminated)
		.hd_ena                 (),                                                                      //                   (terminated)
		.pcs_phase_measure_clk  (1'b0),                                                                  //                   (terminated)
		.rx_latency_adj         (),                                                                      //                   (terminated)
		.tx_latency_adj         (),                                                                      //                   (terminated)
		.tx_ptp_alignment       (),                                                                      //                   (terminated)
		.pcs_eccstatus          ()                                                                       //                   (terminated)
	);
    
	sgmii_pcs_share_altera_lvds_191_xvdv7pi i_lvdsio_rx_0 (
		.rx_in         (i_lvdsio_terminator_0_rx_in_export),           //         rx_in.export
		.rx_out        (i_lvdsio_rx_0_rx_out_export),                  //        rx_out.export
		.rx_coreclock  (i_lvdsio_rx_0_rx_coreclock_export),            //  rx_coreclock.export
		.inclock       (i_lvdsio_terminator_0_lvds_rx_inclock_export), //       inclock.export
		.pll_areset    (i_lvdsio_terminator_0_pll_areset_rx_export),   //    pll_areset.export
		.rx_dpa_locked (i_lvdsio_rx_0_rx_dpa_locked_export),           // rx_dpa_locked.export
		.rx_dpa_reset  (i_lvdsio_terminator_0_rx_dpa_reset_export),    //  rx_dpa_reset.export
		.rx_divfwdclk  (i_lvdsio_rx_0_rx_divfwdclk_export),            //  rx_divfwdclk.export
		.pll_locked    (i_lvdsio_rx_0_pll_locked_export)               //    pll_locked.export
	);

	sgmii_pcs_share_altera_lvds_191_id6gcay i_lvdsio_tx_0 (
		.tx_in      (i_lvdsio_terminator_0_tx_in_export),           //      tx_in.export
		.tx_out     (i_lvdsio_tx_0_tx_out_export),                  //     tx_out.export
		.inclock    (i_lvdsio_terminator_0_lvds_tx_inclock_export), //    inclock.export
		.pll_areset (i_lvdsio_terminator_0_pll_areset_tx_export),   // pll_areset.export
		.pll_locked (i_lvdsio_tx_0_pll_locked_export)               // pll_locked.export
	);

	altera_eth_tse_nf_lvds_terminator #(
		.NUM_CHANNELS       (4),
		.SYNCHRONIZER_DEPTH (3)
	) i_lvdsio_terminator_0 (
		.lvds_inclock              (ref_clk),                                                               //             lvds_inclock.clk
		.reset                     (rst_controller_reset_out_reset),                                        //                 reset_in.reset
		.lvds_rx_inclock           (i_lvdsio_terminator_0_lvds_rx_inclock_export),                          //          lvds_rx_inclock.export
		.pll_areset_rx             (i_lvdsio_terminator_0_pll_areset_rx_export),                            //            pll_areset_rx.export
		.pll_locked_tx             (i_lvdsio_tx_0_pll_locked_export),                                       //            pll_locked_tx.export
		.lvds_tx_inclock           (i_lvdsio_terminator_0_lvds_tx_inclock_export),                          //          lvds_tx_inclock.export
		.rx_coreclock              (i_lvdsio_rx_0_rx_coreclock_export),                                     //             rx_coreclock.export
		.pll_areset_tx             (i_lvdsio_terminator_0_pll_areset_tx_export),                            //            pll_areset_tx.export
		.pll_locked_rx             (i_lvdsio_rx_0_pll_locked_export),                                       //            pll_locked_rx.export
		.rx_dpa_reset              (i_lvdsio_terminator_0_rx_dpa_reset_export),                             //             rx_dpa_reset.export
		.rx_in                     (i_lvdsio_terminator_0_rx_in_export),                                    //                    rx_in.export
		.rx_out                    (i_lvdsio_rx_0_rx_out_export),                                           //                   rx_out.export
		.tx_in                     (i_lvdsio_terminator_0_tx_in_export),                                    //                    tx_in.export
		.rx_dpa_locked             (i_lvdsio_rx_0_rx_dpa_locked_export),                                    //            rx_dpa_locked.export
		.rx_divfwdclk              (i_lvdsio_rx_0_rx_divfwdclk_export),                                     //             rx_divfwdclk.export
		.tx_out                    (i_lvdsio_tx_0_tx_out_export),                                           //                   tx_out.export
        
		.rxp_0                     (rxp_0), //      serial_connection_0.export
		.txp_0                     (txp_0), //                         .export
		.rx_reset_0                (i_lvdsio_terminator_0_rx_reset_0_rx_reset),                             //               rx_reset_0.rx_reset
		.rx_reset_sequence_done_0  (i_lvdsio_terminator_0_rx_reset_sequence_done_0_rx_reset_sequence_done), // rx_reset_sequence_done_0.rx_reset_sequence_done
		.tbi_rx_clk_0              (i_lvdsio_terminator_0_tbi_rx_clk_0_tbi_rx_clk),                         //             tbi_rx_clk_0.tbi_rx_clk
		.tx_reset_0                (i_lvdsio_terminator_0_tx_reset_0_tx_reset),                             //               tx_reset_0.tx_reset
		.tbi_rx_d_lvds_0           (i_lvdsio_terminator_0_tbi_rx_d_lvds_0_tbi_rx_d_lvds),                   //          tbi_rx_d_lvds_0.tbi_rx_d_lvds
		.tbi_tx_d_muxed_0          (i_tse_pcs_0_tbi_tx_d_muxed_tbi_tx_d_muxed),                             //         tbi_tx_d_muxed_0.tbi_tx_d_muxed
        
		.rxp_1                     (rxp_1), //      serial_connection_1.export
		.txp_1                     (txp_1), //                         .export
		.rx_reset_1                (i_lvdsio_terminator_0_rx_reset_1_rx_reset),                             //               rx_reset_1.rx_reset
		.rx_reset_sequence_done_1  (i_lvdsio_terminator_0_rx_reset_sequence_done_1_rx_reset_sequence_done), // rx_reset_sequence_done_1.rx_reset_sequence_done
		.tbi_rx_clk_1              (i_lvdsio_terminator_0_tbi_rx_clk_1_tbi_rx_clk),                         //             tbi_rx_clk_1.tbi_rx_clk
		.tx_reset_1                (i_lvdsio_terminator_0_tx_reset_1_tx_reset),                             //               tx_reset_1.tx_reset
		.tbi_rx_d_lvds_1           (i_lvdsio_terminator_0_tbi_rx_d_lvds_1_tbi_rx_d_lvds),                   //          tbi_rx_d_lvds_1.tbi_rx_d_lvds
		.tbi_tx_d_muxed_1          (i_tse_pcs_1_tbi_tx_d_muxed_tbi_tx_d_muxed),                             //         tbi_tx_d_muxed_1.tbi_tx_d_muxed
        
		.rxp_2                     (rxp_2), //      serial_connection_2.export
		.txp_2                     (txp_2), //                         .export
		.rx_reset_2                (i_lvdsio_terminator_0_rx_reset_2_rx_reset),                             //               rx_reset_2.rx_reset
		.rx_reset_sequence_done_2  (i_lvdsio_terminator_0_rx_reset_sequence_done_2_rx_reset_sequence_done), // rx_reset_sequence_done_2.rx_reset_sequence_done
		.tbi_rx_clk_2              (i_lvdsio_terminator_0_tbi_rx_clk_2_tbi_rx_clk),                         //             tbi_rx_clk_2.tbi_rx_clk
		.tx_reset_2                (i_lvdsio_terminator_0_tx_reset_2_tx_reset),                             //               tx_reset_2.tx_reset
		.tbi_rx_d_lvds_2           (i_lvdsio_terminator_0_tbi_rx_d_lvds_2_tbi_rx_d_lvds),                   //          tbi_rx_d_lvds_2.tbi_rx_d_lvds
		.tbi_tx_d_muxed_2          (i_tse_pcs_2_tbi_tx_d_muxed_tbi_tx_d_muxed),                             //         tbi_tx_d_muxed_2.tbi_tx_d_muxed
        
		.rxp_3                     (rxp_3), //      serial_connection_3.export
		.txp_3                     (txp_3), //                         .export
		.rx_reset_3                (i_lvdsio_terminator_0_rx_reset_3_rx_reset),                             //               rx_reset_3.rx_reset
		.rx_reset_sequence_done_3  (i_lvdsio_terminator_0_rx_reset_sequence_done_3_rx_reset_sequence_done), // rx_reset_sequence_done_3.rx_reset_sequence_done
		.tbi_rx_clk_3              (i_lvdsio_terminator_0_tbi_rx_clk_3_tbi_rx_clk),                         //             tbi_rx_clk_3.tbi_rx_clk
		.tx_reset_3                (i_lvdsio_terminator_0_tx_reset_3_tx_reset),                             //               tx_reset_3.tx_reset
		.tbi_rx_d_lvds_3           (i_lvdsio_terminator_0_tbi_rx_d_lvds_3_tbi_rx_d_lvds),                   //          tbi_rx_d_lvds_3.tbi_rx_d_lvds
		.tbi_tx_d_muxed_3          (i_tse_pcs_3_tbi_tx_d_muxed_tbi_tx_d_muxed),                             //         tbi_tx_d_muxed_3.tbi_tx_d_muxed
        
		.rxp_4                     (1'b0),                                                                  //              (terminated)
		.txp_4                     (),                                                                      //              (terminated)
		.rx_reset_4                (),                                                                      //              (terminated)
		.rx_reset_sequence_done_4  (),                                                                      //              (terminated)
		.tbi_rx_clk_4              (),                                                                      //              (terminated)
		.tx_reset_4                (),                                                                      //              (terminated)
		.tbi_rx_d_lvds_4           (),                                                                      //              (terminated)
		.tbi_tx_d_muxed_4          (10'b0000000000),                                                        //              (terminated)
        
		.rxp_5                     (1'b0),                                                                  //              (terminated)
		.txp_5                     (),                                                                      //              (terminated)
		.rx_reset_5                (),                                                                      //              (terminated)
		.rx_reset_sequence_done_5  (),                                                                      //              (terminated)
		.tbi_rx_clk_5              (),                                                                      //              (terminated)
		.tx_reset_5                (),                                                                      //              (terminated)
		.tbi_rx_d_lvds_5           (),                                                                      //              (terminated)
		.tbi_tx_d_muxed_5          (10'b0000000000),                                                        //              (terminated)
        
		.rxp_6                     (1'b0),                                                                  //              (terminated)
		.txp_6                     (),                                                                      //              (terminated)
		.rx_reset_6                (),                                                                      //              (terminated)
		.rx_reset_sequence_done_6  (),                                                                      //              (terminated)
		.tbi_rx_clk_6              (),                                                                      //              (terminated)
		.tx_reset_6                (),                                                                      //              (terminated)
		.tbi_rx_d_lvds_6           (),                                                                      //              (terminated)
		.tbi_tx_d_muxed_6          (10'b0000000000),                                                        //              (terminated)
        
		.rxp_7                     (1'b0),                                                                  //              (terminated)
		.txp_7                     (),                                                                      //              (terminated)
		.rx_reset_7                (),                                                                      //              (terminated)
		.rx_reset_sequence_done_7  (),                                                                      //              (terminated)
		.tbi_rx_clk_7              (),                                                                      //              (terminated)
		.tx_reset_7                (),                                                                      //              (terminated)
		.tbi_rx_d_lvds_7           (),                                                                      //              (terminated)
		.tbi_tx_d_muxed_7          (10'b0000000000),                                                        //              (terminated)
        
		.rxp_8                     (1'b0),                                                                  //              (terminated)
		.txp_8                     (),                                                                      //              (terminated)
		.rx_reset_8                (),                                                                      //              (terminated)
		.rx_reset_sequence_done_8  (),                                                                      //              (terminated)
		.tbi_rx_clk_8              (),                                                                      //              (terminated)
		.tx_reset_8                (),                                                                      //              (terminated)
		.tbi_rx_d_lvds_8           (),                                                                      //              (terminated)
		.tbi_tx_d_muxed_8          (10'b0000000000),                                                        //              (terminated)
        
		.rxp_9                     (1'b0),                                                                  //              (terminated)
		.txp_9                     (),                                                                      //              (terminated)
		.rx_reset_9                (),                                                                      //              (terminated)
		.rx_reset_sequence_done_9  (),                                                                      //              (terminated)
		.tbi_rx_clk_9              (),                                                                      //              (terminated)
		.tx_reset_9                (),                                                                      //              (terminated)
		.tbi_rx_d_lvds_9           (),                                                                      //              (terminated)
		.tbi_tx_d_muxed_9          (10'b0000000000),                                                        //              (terminated)
        
		.rxp_10                    (1'b0),                                                                  //              (terminated)
		.txp_10                    (),                                                                      //              (terminated)
		.rx_reset_10               (),                                                                      //              (terminated)
		.rx_reset_sequence_done_10 (),                                                                      //              (terminated)
		.tbi_rx_clk_10             (),                                                                      //              (terminated)
		.tx_reset_10               (),                                                                      //              (terminated)
		.tbi_rx_d_lvds_10          (),                                                                      //              (terminated)
		.tbi_tx_d_muxed_10         (10'b0000000000),                                                        //              (terminated)
        
		.rxp_11                    (1'b0),                                                                  //              (terminated)
		.txp_11                    (),                                                                      //              (terminated)
		.rx_reset_11               (),                                                                      //              (terminated)
		.rx_reset_sequence_done_11 (),                                                                      //              (terminated)
		.tbi_rx_clk_11             (),                                                                      //              (terminated)
		.tx_reset_11               (),                                                                      //              (terminated)
		.tbi_rx_d_lvds_11          (),                                                                      //              (terminated)
		.tbi_tx_d_muxed_11         (10'b0000000000)                                                         //              (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (reset),                          // reset_in0.reset
		.clk            (ref_clk),                        //       clk.clk
		.reset_out      (rst_controller_reset_out_reset), // reset_out.reset
		.reset_req      (),                               // (terminated)
		.reset_req_in0  (1'b0),                           // (terminated)
		.reset_in1      (1'b0),                           // (terminated)
		.reset_req_in1  (1'b0),                           // (terminated)
		.reset_in2      (1'b0),                           // (terminated)
		.reset_req_in2  (1'b0),                           // (terminated)
		.reset_in3      (1'b0),                           // (terminated)
		.reset_req_in3  (1'b0),                           // (terminated)
		.reset_in4      (1'b0),                           // (terminated)
		.reset_req_in4  (1'b0),                           // (terminated)
		.reset_in5      (1'b0),                           // (terminated)
		.reset_req_in5  (1'b0),                           // (terminated)
		.reset_in6      (1'b0),                           // (terminated)
		.reset_req_in6  (1'b0),                           // (terminated)
		.reset_in7      (1'b0),                           // (terminated)
		.reset_req_in7  (1'b0),                           // (terminated)
		.reset_in8      (1'b0),                           // (terminated)
		.reset_req_in8  (1'b0),                           // (terminated)
		.reset_in9      (1'b0),                           // (terminated)
		.reset_req_in9  (1'b0),                           // (terminated)
		.reset_in10     (1'b0),                           // (terminated)
		.reset_req_in10 (1'b0),                           // (terminated)
		.reset_in11     (1'b0),                           // (terminated)
		.reset_req_in11 (1'b0),                           // (terminated)
		.reset_in12     (1'b0),                           // (terminated)
		.reset_req_in12 (1'b0),                           // (terminated)
		.reset_in13     (1'b0),                           // (terminated)
		.reset_req_in13 (1'b0),                           // (terminated)
		.reset_in14     (1'b0),                           // (terminated)
		.reset_req_in14 (1'b0),                           // (terminated)
		.reset_in15     (1'b0),                           // (terminated)
		.reset_req_in15 (1'b0)                            // (terminated)
	);

endmodule
