config sgmii_pcs_share_altera_lvds_191_id6gcay_cfg;
		design sgmii_pcs_share_altera_lvds_191_id6gcay;
		instance sgmii_pcs_share_altera_lvds_191_id6gcay.core use sgmii_pcs_share_altera_lvds_core20_191.sgmii_pcs_share_altera_lvds_core20_191_446yfoq;
endconfig

